export const INS_PERSONALS_REQUEST = "INS_PERSONALS_REQUEST";
export const INS_PERSONALS_SUCCESS = "INS_PERSONALS_SUCCESS";
export const INS_PERSONALS_FAILURE = "INS_PERSONALS_FAILURE";

export const ADD_INS_PERSONALS_REQUEST = "ADD_INS_PERSONALS_REQUEST";
export const ADD_INS_PERSONALS_SUCCESS = "ADD_INS_PERSONALS_SUCCESS";
export const ADD_INS_PERSONALS_FAILURE = "ADD_INS_PERSONALS_FAILURE";

export const DELETE_INS_PERSONALS_REQUEST = "DELETE_INS_PERSONALS_REQUEST";
export const DELETE_INS_PERSONALS_SUCCESS = "DELETE_INS_PERSONALS_SUCCESS";
export const DELETE_INS_PERSONALS_FAILURE = "DELETE_INS_PERSONALS_FAILURE";
